Support to rampup clients and wait between message
krylovsk/mqtt-benchmark pull request #26
Opened 2022-01-19 13:15 UTC by sreekesh93

Currently clients just rampup without control to produce load in constant phase rampup time is required in performance/load testing.

2022-02-15 05:04 UTC, sreekesh93 commented
@krylovsk Can you please review this PR?

2022-02-18 08:59 UTC, krylovsk requested changes
Thanks for the contribution (and sorry for late response). Please check the comments.

2022-02-18 08:59 UTC, krylovsk commented on main.go
> +        time.Sleep(time.Duration(sleepTime * 1000) * time.milliseconds)
```suggestion
        time.Sleep(time.Duration(sleepTime * 1000) * time.Millisecond)
```
typo?

2022-02-22 04:11 UTC, sreekesh93 commented
> Thanks for the contribution (and sorry for late response). Please check the comments.

Thanks for reviewing applied the changes suggested

2022-02-22 06:35 UTC, krylovsk approved these changes

2022-02-22 06:36 UTC, merged